version: '3'

services:
  appnode:
    container_name: appnode
    build: .
    ports:
      - "$PORT_LOCAL_NODE:$PORT"
    env_file:
      - ./.env
    environment:
      - PORT=$PORT
    depends_on:
      - bd_mysql
  
  bd_mysql:
    image: mariadb:jammy
    container_name: bd_mysql
    environment:
      - MARIADB_ROOT_PASSWORD=$DB_PASSWORD_ROOT
      - MARIADB_USER=$BD_USER
      - MARIADB_PASSWORD=$BD_PASSWORD
      - MARIADB_DATABASE=$BD_DATABASE
    ports:
      - "3308:3306"
  
  webserver:
    image: nginx:1.25.4-alpine
    container_name: webserver
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - appnode
  
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email cchura.cpc@gmail.com --agree-tos -d dockernode.edtics.com
    depends_on:
      - webserver

volumes:
  certbot-etc:
  certbot-var:
  web-root:
      
