version: '3'

services:
  appnode:
    container_name: appnode
    build: .
    ports:
      - "$PORT_LOCAL_NODE:$PORT"
    env_file:
      - ./.env
    environment:
      - PORT=$PORT
    depends_on:
      - bd_mysql
  
  bd_mysql:
    image: mariadb:jammy
    container_name: bd_mysql
    environment:
      - MARIADB_ROOT_PASSWORD=$DB_PASSWORD_ROOT
      - MARIADB_USER=$BD_USER
      - MARIADB_PASSWORD=$BD_PASSWORD
      - MARIADB_DATABASE=$BD_DATABASE
    ports:
      - "3308:3306"
  
  webserver:
    image: nginx:1.25.4-alpine
    container_name: webserver
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - appnode

      
